name: DeepSeek Config
version: 1.0.0
schema: v1

# https://docs.continue.dev/customization/models
models:
  - name: DeepSeek V3 (Chat)
    provider: openai
    model: deepseek-chat
    apiKey: sk-488e3b6f40d348cf987961433b2fbb06
    apiBase: https://api.deepseek.com/v1 

tabAutocompleteModel:
  name: DeepSeek Coder V2 (FIM)
  provider: openai
  model: deepseek-coder
  apiKey: sk-488e3b6f40d348cf987961433b2fbb06
  apiBase: https://api.deepseek.com/beta
    
    
contextProviders:
  - name: code
  - name: docs
  - name: folder
# MCP Servers
mcpServers:
  - uses: anthropic/memory-mcp